---
- name: Create Apache & AWX Boxes
  hosts: apache

  roles:

  - role: dynatrace.oneagent
    oneagent_installer_script_url: INSTALLER_URL_HERE

  - role: geerlingguy.apache
    become: yes

  post_tasks:

  - name: Install PHP
    become: yes
    package:
      name: php70
      state: present

  - name: Install Git
    become: yes
    package:
      name: git
      state: present

  - name: Restart httpd
    become: yes
    service:
      name: httpd
      state: restarted

- name: Install AWX
  hosts: awx
  become: yes

  vars:
    ansible_distribution_major_version: 6

  pre_tasks:

  - name: Install Git
    package:
      name: git
      state: present

  - name: Install Python Pip
    package:
      name: python-pip
      state: present

  - name: Install Docker
    package:
      name: docker
      state: present

  - name: Install Docker PY
    command: pip install docker-py

  - name: Start Docker
    service:
      name: docker
      state: started

  roles:

  - role: geerlingguy.ansible
  - role: geerlingguy.nodejs
  - role: geerlingguy.awx
