---
- name: Send DT Event
  hosts: all
  gather_facts: no

  tasks:
  - name: Send DT Event
    docker_container:
      state: started
      name: dtpushevent
      image: dynatraceacm/push-event:0.1.0
      env:
          dict: {{ my_dict }}
