---
- name: Echo Test
  hosts: all

  tasks:
    - name: Print Echo Message
      debug: msg="Hello, world"
      
    - name: Print Foo
      debug: msg="Foo is {{ foo }}"

    - name: Print foo_bar
      debug: msg="foo_bar is {{ foo_bar }}"
      
    - name: Print something
      debug: msg="{{ dt_env_url }}"
