---
- name: Echo Test
  hosts: all

  tasks:
    - name: Print Echo Message
      debug: msg="Hello, world"
      
    - name: Print Foo
      debug: msg="Foo is {{ foo }}"

    - name: Print foobar
      debug: msg="foo-bar is {{ foo-bar }}"
      
    - name: Print something
      debug: msg="{{ dt-env-url }}"
